SUBDIRS=tgraph qt ClientServer
.PHONY: md $(SUBDIRS)
	
all: md $(SUBDIRS)

$(SUBDIRS):
	make -C $@ -e -f gnumakefile $(TARGET)
		
md:
	@if ! test -d lib ; then mkdir lib ; fi
    
static:TARGET=static
static: all    

clean:TARGET=clean
clean: all
	
unix:
	cd tgraph ; dos2unix -k *.cpp
	cd qt ; dos2unix -k *.h ; dos2unix -k *.cpp
	cd incl ; dos2unix -k *.h 
	cd incl/TAXI ; dos2unix -k *.h 
	cd incl/QT ; dos2unix -k *.h 


# DO NOT DELETE
