all: libtgraph  libqt

libtgraph : tgraph/*.cpp
	cd tgraph ;make -f gnumakefile -e

libqt : qt/*.cpp
	cd qt ;make -f gnumakefile -e

clean:
	cd tgraph ; make -f gnumakefile -e clean
	cd qt ; make -f gnumakefile -e clean
	cd incl/TAXI ;rm -f *~ *.hh
unix:
	cd tgraph ; dos2unix -k *.cpp
	cd qt ; dos2unix -k *.h ; dos2unix -k *.cpp
	cd incl ; dos2unix -k *.h 
	cd incl/TAXI ; dos2unix -k *.h 
	cd incl/QT ; dos2unix -k *.h 

rebuild:
	cd tgraph ; touch *.cpp
	cd qt ; touch *.cpp

depend:
	cd tgraph ;make -f gnumakefile -e depend
	cd qt ;make -f gnumakefile -e depend
	cd ClientServer ;make -f gnumakefile -e depend

nodepend:
	cd tgraph ;make -f gnumakefile -e nodepend
	cd qt ;make -f gnumakefile -e nodepend	


# DO NOT DELETE
