MQTDIR = /usr/local/Trolltech/Qt-4.5.0
QTINCLUDE= /usr/local/Trolltech/Qt-4.5.0/include/Qt
QTLRELEASE= /usr/local/Trolltech/Qt-4.5.0/bin/lrelease
QTLUPDATE= /usr/local/Trolltech/Qt-4.5.0/bin/lupdate
#version of the library
VERSION= 1.3.3
MODE = release
DISTPATH = /home/pigale/pigale
AWK = gawk
ENABLE_STATIC = yes
QMAKE_CXXFLAGS_RELEASE =  -march=i686
#debug_level 1-normal (used for profiler) 2-check arrays (slow)
DEBUG_LEVEL = 1


