####################### MAY NEED EDITING ########################
#Compiler options
CC=g++
#CPU="-mcpu=i686"
CPU=
#OPT: if set to dbg > debug version
#OPT: if set to opt > optimised version
OPT=opt

#libray paths
#MQTDIR=/usr/lib/qt4
MQTDIR=/usr/local/Trolltech/Qt-4.1.1

UNIXLIB =  -L$(MQTDIR)/lib -lQt3Support -lQtGui -lQtXml -lQtCore -lQtOpenGL -L/usr/X11R6/lib -lglut -lGL -lGLU 
UNIXLIB += -lpng -lSM -lICE -lz -lXi -lXrender -lXrandr -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lm -ldl -lpthread


#include paths
IFLAGS =  -idirafter$(MQTDIR)/include
IFLAGS +=  -idirafter$(MQTDIR)/include/Qt
IFLAGS += -idirafter$(MQTDIR)/include/Qt3Support 
#IFLAGS += -idirafter$(MQTDIR)/include/QtTest
IFLAGS += -I$(PIGALEPATH)/incl
#awk 
AWK=awk
####################### END EDITING #########################
PIGALEPATH=..
PIGALELIB =  -L$(PIGALEPATH)/lib    -lpigaleQt$(OPT).la -ltgraph$(OPT).la
NVERSION=BETA
# P = name of output program

MMOC=$(MQTDIR)/bin/moc


#GENERAL OPTIONS
.SUFFIXES:.cpp .o .obj .opt .dbg
#OPTIMIZED OPTIONS
CFLAGSopt = -O3  $(PIC) $(CPU)
#CFLAGSopt +=  -Wall -Wpointer-arith  -pipe
CFLAGSopt +=  -Wall -Wpointer-arith -Werror  -pipe
CFLAGSopt +=  -fomit-frame-pointer 
CFLAGSopt +=  -DQT -DVERSION_$(NVERSION) 
CFLAGSopt +=  -DQT_THREAD_SUPPORT 
CFLAGSopt +=  -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_SHARED
CFLAGSopt +=  -D_QT4_

#DEBUGGING OPTIONS
CFLAGSdbg  =  -g -Wall $(PIC) $(CPU)
CFLAGSdbg +=  -Wpointer-arith -pipe
CFLAGSdbg +=  -DTDEBUG
CFLAGSdbg +=  -DQT -DVERSION_$(NVERSION)
CFLAGSdbg +=  -DQT_THREAD_SUPPORT 
CFLAGSdbg +=  -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_GUI_LIB -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_SHARED
CFLAGSdbg +=  -D_QT4_

CFLAGS  = $(CFLAGS$(OPT))
VPATH   = ./.obj


all : md client

$(PIGALEPATH)/incl/QT/Action.h:$(PIGALEPATH)/incl/QT/Action_def.h
	$(AWK) -f Action.awk $(PIGALEPATH)/incl/QT/Action_def.h > $(PIGALEPATH)/incl/QT/Action.h
 

static:
client: client.h client.cpp  
	$(CC) -c $(CFLAGS) $(IFLAGS) -o $(VPATH)/client.o client.cpp 
	$(MMOC) client.h -o moc_client.cpp
	$(CC) -c $(CFLAGS) $(IFLAGS) -o $(VPATH)/moc_client.o moc_client.cpp 
	$(CC)  $(CFLAGS) -o client   $(VPATH)/client.o $(VPATH)/moc_client.o $(UNIXLIB) 

clean:
	@rm -f *~ *bak *.flc  moc_*.cpp  $(OBJ) $(DLIB)

md:
	@if ! test -d .obj ; then mkdir .obj ; fi

depend:
	@makedepend -o.$(OPT) -f gnumakefile $(DFLAGS)  -Y client.cpp 2> /dev/null

nodepend:
	@makedepend -o.$(OPT) -f gnumakefile  -Y  2> /dev/null



.PHONY: md all
# DO NOT DELETE

client.dbg: client.h
