####################### MAY NEED EDITING ########################
#Compiler options
CC=g++
#CPU="-mcpu=i686"
#CPU=-m686 
CPU=
OPT=opt
#PIC if wanted shared dynamic libraries
PIC=-fpic

#Unix libraries to be linked (system dependent)
#UNIXLIB =  -L$(MQTDIR)/lib -lqt-mt -L/usr/X11R6/lib -lglut -lGL -lGLU  
UNIXLIB = -L/usr/X11R6/lib -lX11
AWK=awk
####################### END EDITING #########################
PIGALEPATH=../../pigale
SAMPLING =
RAN = ranlib
#SAMPLING = -lc_p
L = tgraph
#GENERAL OPTIONS
.SUFFIXES:.cpp .c .opt .dbg .o 
IFLAGS = -I$(PIGALEPATH)/incl 

#OPTIMIZED OPTIONS
CFLAGSopt = -O3   $(PIC) $(CPU)
CFLAGSopt += -Wall -Wstrict-prototypes -Wpointer-arith -Werror -pipe
CFLAGSopt +=  -fomit-frame-pointer

#DEBUGGING OPTIONS (-pg -a for sampling)
CFLAGSdbg  =  -g -Wall -Wstrict-prototypes -Wpointer-arith -Werror -pipe $(PIC) $(CPU)
CFLAGSdbg +=  -DTDEBUG

DLIB    = $(PIGALEPATH)/lib/lib$L$(OPT).so
LIBS    = -L$(PIGALEPATH)/lib -ltgraph$(OPT)
CFLAGS  = $(CFLAGS$(OPT))
VPATH   = ./.obj
FILES   :=  $(wildcard *.cpp)
SPECIAL := PropName.cpp
FILES   := $(filter-out $(SPECIAL), $(FILES))
FILES2  := $(FILES)
FILES2  += $(SPECIAL)
OBJECTS =  $(patsubst %.cpp,%.$(OPT), $(FILES2))
OBJ =  $(patsubst %.$(OPT),$(VPATH)/%.$(OPT), $(OBJECTS))

all :  $(DLIB)

PropName.cpp : $(PIGALEPATH)/incl/TAXI/propdef.h
	$(AWK) -f propname.awk $(PIGALEPATH)/incl/TAXI/propdef.h > PropName.cpp

.cpp.$(OPT): $*.cpp 
	$(CC) -c $(CFLAGS) $(IFLAGS) -o  $(VPATH)/$*.$(OPT)   $*.cpp

$(DLIB):	 md $(OBJECTS)
	@rm -f $(PIGALEPATH)/lib/lib$L$(OPT).so
	$(CC) -shared  -o $(PIGALEPATH)/lib/lib$L$(OPT).so  $(OBJ)

clean:
	@rm -f *~ *bak *.flc $(OBJ) *.flc $(DLIB)

depend:
	@makedepend -o.$(OPT) -f gnumakefile $(IFLAGS)  -Y $(FILES) 2> /dev/null

nodepend:
	@makedepend -o.$(OPT) -f gnumakefile  -Y  2> /dev/null

list:
	../makelist *.cpp >Make.lst
	
md:depend
	@if ! test -d .obj ; then mkdir .obj ; fi
test:
	@echo OBJ=$(OBJ)
	@echo OBJECTS=$(OBJECTS)

.PHONY: md all
# DO NOT DELETE

3-ConOrientTriang.opt: ../../pigale/incl/TAXI/KantShel.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/graphs.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tbase.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/graph.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/elmt.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tprop.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tsvector.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tdebug.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Errors.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tpropio.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tstring.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/propdef.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tpoint.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/IntList.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tflist.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tstack.h
3-ConOrientTriang.opt: ../../pigale/incl/TAXI/Tarray.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tmessage.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/graphs.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tbase.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/graph.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/elmt.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tprop.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tsvector.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tdebug.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Errors.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tpropio.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tstring.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/propdef.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/Tpoint.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/color.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/KantShel.h
3-ConShelling1.opt: ../../pigale/incl/TAXI/IntList.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/KantShel.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/graphs.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tbase.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/graph.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/elmt.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tprop.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tsvector.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tdebug.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Errors.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tpropio.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tstring.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/propdef.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tpoint.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/IntList.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/color.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tmessage.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tflist.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tstack.h
3-ConShelling2.opt: ../../pigale/incl/TAXI/Tarray.h
Barycenter.opt: ../../pigale/incl/TAXI/Tbase.h
Barycenter.opt: ../../pigale/incl/TAXI/graphs.h
Barycenter.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Barycenter.opt: ../../pigale/incl/TAXI/Tprop.h
Barycenter.opt: ../../pigale/incl/TAXI/Tsvector.h
Barycenter.opt: ../../pigale/incl/TAXI/Tdebug.h
Barycenter.opt: ../../pigale/incl/TAXI/Errors.h
Barycenter.opt: ../../pigale/incl/TAXI/Tpropio.h
Barycenter.opt: ../../pigale/incl/TAXI/Tstring.h
Barycenter.opt: ../../pigale/incl/TAXI/propdef.h
Barycenter.opt: ../../pigale/incl/TAXI/Tpoint.h
Barycenter.opt: ../../pigale/incl/TAXI/Tmessage.h
Barycenter.opt: ../../pigale/incl/TAXI/smatrix.h
BFS.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tbase.h
BFS.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
BFS.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
BFS.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
BFS.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
BFS.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
BFS.opt: ../../pigale/incl/TAXI/Tsmap.h
Biconnect.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/color.h
Biconnect.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Biconnect.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Biconnect.opt: ../../pigale/incl/TAXI/Tsvector.h
Biconnect.opt: ../../pigale/incl/TAXI/Tdebug.h
Biconnect.opt: ../../pigale/incl/TAXI/Errors.h
Biconnect.opt: ../../pigale/incl/TAXI/Tpropio.h
Biconnect.opt: ../../pigale/incl/TAXI/Tstring.h
Biconnect.opt: ../../pigale/incl/TAXI/propdef.h
Biconnect.opt: ../../pigale/incl/TAXI/Tpoint.h
Biconnect.opt: ../../pigale/incl/TAXI/IntList.h
Bipolar.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tbase.h
Bipolar.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Bipolar.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
Bipolar.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Bipolar.opt: ../../pigale/incl/TAXI/Tpropio.h
Bipolar.opt: ../../pigale/incl/TAXI/Tstring.h
Bipolar.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
Bipolar.opt: ../../pigale/incl/TAXI/Tmessage.h ../../pigale/incl/TAXI/color.h
Bipolar.opt: ../../pigale/incl/TAXI/DFSGraph.h
BipPlanarize.opt: ../../pigale/incl/TAXI/graphs.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tbase.h
BipPlanarize.opt: ../../pigale/incl/TAXI/graph.h
BipPlanarize.opt: ../../pigale/incl/TAXI/elmt.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tprop.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tsvector.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tdebug.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Errors.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tpropio.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tstring.h
BipPlanarize.opt: ../../pigale/incl/TAXI/propdef.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tpoint.h
BipPlanarize.opt: ../../pigale/incl/TAXI/color.h
BipPlanarize.opt: ../../pigale/incl/TAXI/Tmessage.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tbase.h
CotreeCritical.opt: ../../pigale/incl/TAXI/CotreeCritical.h
CotreeCritical.opt: ../../pigale/incl/TAXI/DFSGraph.h
CotreeCritical.opt: ../../pigale/incl/TAXI/color.h
CotreeCritical.opt: ../../pigale/incl/TAXI/graphs.h
CotreeCritical.opt: ../../pigale/incl/TAXI/graph.h
CotreeCritical.opt: ../../pigale/incl/TAXI/elmt.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tprop.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tsvector.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tdebug.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Errors.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tpropio.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tstring.h
CotreeCritical.opt: ../../pigale/incl/TAXI/propdef.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tpoint.h
CotreeCritical.opt: ../../pigale/incl/TAXI/Tmessage.h
CotreeCritical.opt: ../../pigale/incl/TAXI/DFSLow.h
CotreeCritical.opt: ../../pigale/incl/TAXI/lralgo.h
CotreeCritical.opt: ../../pigale/incl/TAXI/bicon.h
Debug.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tdebug.h
Debug.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tmessage.h
Debug.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Debug.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Debug.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tpropio.h
Debug.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Debug.opt: ../../pigale/incl/TAXI/Tpoint.h
DFS.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graphs.h
DFS.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
DFS.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
DFS.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
DFS.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
DFS.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
DFS.opt: ../../pigale/incl/TAXI/bicon.h ../../pigale/incl/TAXI/color.h
DFSGraph.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/DFSLow.h
DFSGraph.opt: ../../pigale/incl/TAXI/color.h
DFSGraph.opt: ../../pigale/incl/TAXI/DFSGraph.h
DFSGraph.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
DFSGraph.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
DFSGraph.opt: ../../pigale/incl/TAXI/Tsvector.h
DFSGraph.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
DFSGraph.opt: ../../pigale/incl/TAXI/Tpropio.h
DFSGraph.opt: ../../pigale/incl/TAXI/Tstring.h
DFSGraph.opt: ../../pigale/incl/TAXI/propdef.h
DFSGraph.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/lralgo.h
DFSGraph.opt: ../../pigale/incl/TAXI/bicon.h
DFSMap.opt: ../../pigale/incl/TAXI/DFSLow.h ../../pigale/incl/TAXI/Tbase.h
DFSMap.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/DFSGraph.h
DFSMap.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
DFSMap.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
DFSMap.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
DFSMap.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
DFSMap.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
DFSMap.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/lralgo.h
DFSMap.opt: ../../pigale/incl/TAXI/bicon.h ../../pigale/incl/TAXI/embed.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tbase.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tdebug.h
Diagonalise.opt: ../../pigale/incl/TAXI/Errors.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tmessage.h
Diagonalise.opt: ../../pigale/incl/TAXI/graphs.h
Diagonalise.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tprop.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tsvector.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tpropio.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tstring.h
Diagonalise.opt: ../../pigale/incl/TAXI/propdef.h
Diagonalise.opt: ../../pigale/incl/TAXI/Tpoint.h
Diagonalise.opt: ../../pigale/incl/TAXI/netcut.h
Diagonalise.opt: ../../pigale/incl/TAXI/embedrn.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tbase.h
Embed2Pages.opt: ../../pigale/incl/TAXI/graphs.h
Embed2Pages.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tprop.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tsvector.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tdebug.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Errors.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tpropio.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tstring.h
Embed2Pages.opt: ../../pigale/incl/TAXI/propdef.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tpoint.h
Embed2Pages.opt: ../../pigale/incl/TAXI/IntList.h
Embed2Pages.opt: ../../pigale/incl/TAXI/Tmessage.h
Embed2Pages.opt: ../../pigale/incl/TAXI/color.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graphs.h
EmbedCCD.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tprop.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tsvector.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tpropio.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tstring.h
EmbedCCD.opt: ../../pigale/incl/TAXI/propdef.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tpoint.h
EmbedCCD.opt: ../../pigale/incl/TAXI/SchnyderWood.h
EmbedCCD.opt: ../../pigale/incl/TAXI/IntList.h ../../pigale/incl/TAXI/color.h
EmbedCCD.opt: ../../pigale/incl/TAXI/Tstack.h ../../pigale/incl/TAXI/Tarray.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graphs.h
EmbedFPP.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tprop.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tsvector.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tpropio.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tstring.h
EmbedFPP.opt: ../../pigale/incl/TAXI/propdef.h
EmbedFPP.opt: ../../pigale/incl/TAXI/Tpoint.h
EmbedFPP.opt: ../../pigale/incl/TAXI/SchPack.h
EmbedFPP.opt: ../../pigale/incl/TAXI/IntList.h
EmbedFPP.opt: ../../pigale/incl/TAXI/MaxPath.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tbase.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/graphs.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/graph.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/elmt.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tprop.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tsvector.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tdebug.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Errors.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tpropio.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tstring.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/propdef.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tpoint.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/Tmessage.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/MaxPath.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/color.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/SchPack.h
EmbedPolyline.opt: ../../pigale/incl/TAXI/IntList.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tbase.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/graphs.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/graph.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/elmt.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tprop.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tsvector.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tdebug.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Errors.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tpropio.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tstring.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/propdef.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tpoint.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/Tmessage.h
EmbedTutteCircle.opt: ../../pigale/incl/TAXI/color.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tbase.h
EmbedVision.opt: ../../pigale/incl/TAXI/graphs.h
EmbedVision.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tprop.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tsvector.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tdebug.h
EmbedVision.opt: ../../pigale/incl/TAXI/Errors.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tpropio.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tstring.h
EmbedVision.opt: ../../pigale/incl/TAXI/propdef.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tpoint.h
EmbedVision.opt: ../../pigale/incl/TAXI/Tmessage.h
EmbedVision.opt: ../../pigale/incl/TAXI/MaxPath.h
EmbedVision.opt: ../../pigale/incl/TAXI/color.h
FastTwit.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/lralgo.h
FastTwit.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
FastTwit.opt: ../../pigale/incl/TAXI/Tprop.h
FastTwit.opt: ../../pigale/incl/TAXI/Tsvector.h
FastTwit.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
FastTwit.opt: ../../pigale/incl/TAXI/Tpropio.h
FastTwit.opt: ../../pigale/incl/TAXI/Tstring.h
FastTwit.opt: ../../pigale/incl/TAXI/propdef.h
FastTwit.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tpoint.h
FastTwit.opt: ../../pigale/incl/TAXI/DFSGraph.h
FastTwit.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/bicon.h
File.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tstring.h
File.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
File.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
File.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
File.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/propdef.h
File.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/Tgf.h
File.opt: ../../pigale/incl/TAXI/Tproptgf.h ../../pigale/incl/TAXI/Tfile.h
File.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tsmap.h
File.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tmessage.h
Generate.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/Tbase.h
Generate.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Generate.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Generate.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Generate.opt: ../../pigale/incl/TAXI/Tsvector.h
Generate.opt: ../../pigale/incl/TAXI/Tpropio.h
Generate.opt: ../../pigale/incl/TAXI/Tstring.h
Generate.opt: ../../pigale/incl/TAXI/propdef.h
Generate.opt: ../../pigale/incl/TAXI/random.h ../../pigale/incl/TAXI/Tstack.h
Generate.opt: ../../pigale/incl/TAXI/Tarray.h
GeoAlgs.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/smatrix.h
GeoAlgs.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/elmt.h
GeoAlgs.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
GeoAlgs.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/Tpoint.h
GeoAlgs.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
GeoAlgs.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tpropio.h
GeoAlgs.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/color.h
Graph.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tpoint.h
Graph.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Graph.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Graph.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Graph.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Graph.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Graph.opt: ../../pigale/incl/TAXI/bicon.h ../../pigale/incl/TAXI/Tmessage.h
Graph.opt: ../../pigale/incl/TAXI/color.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tbase.h
k-InfOrient.opt: ../../pigale/incl/TAXI/graphs.h
k-InfOrient.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tprop.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tsvector.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tdebug.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Errors.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tpropio.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tstring.h
k-InfOrient.opt: ../../pigale/incl/TAXI/propdef.h
k-InfOrient.opt: ../../pigale/incl/TAXI/Tpoint.h
k-InfOrient.opt: ../../pigale/incl/TAXI/IntList.h
LR-Algo.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graph.h
LR-Algo.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
LR-Algo.opt: ../../pigale/incl/TAXI/Tsvector.h
LR-Algo.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
LR-Algo.opt: ../../pigale/incl/TAXI/Tpropio.h
LR-Algo.opt: ../../pigale/incl/TAXI/Tstring.h
LR-Algo.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/graphs.h
LR-Algo.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/bicon.h
LR-Algo.opt: ../../pigale/incl/TAXI/lralgo.h
LR-Algo.opt: ../../pigale/incl/TAXI/DFSGraph.h ../../pigale/incl/TAXI/color.h
LR-Map.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
LR-Map.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tprop.h
LR-Map.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
LR-Map.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
LR-Map.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
LR-Map.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tpoint.h
LR-Map.opt: ../../pigale/incl/TAXI/bicon.h ../../pigale/incl/TAXI/lralgo.h
LR-Map.opt: ../../pigale/incl/TAXI/DFSGraph.h ../../pigale/incl/TAXI/color.h
LR-Map.opt: ../../pigale/incl/TAXI/embed.h ../../pigale/incl/TAXI/DFSLow.h
LR-Map.opt: ../../pigale/incl/TAXI/Tmessage.h
mark.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tbase.h
mark.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
mark.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
mark.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
mark.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
mark.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
mark.opt: ../../pigale/incl/TAXI/bicon.h ../../pigale/incl/TAXI/Tmessage.h
MaxPlanar.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tprop.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Tsvector.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Tdebug.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Errors.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Tpropio.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Tstring.h
MaxPlanar.opt: ../../pigale/incl/TAXI/propdef.h
MaxPlanar.opt: ../../pigale/incl/TAXI/color.h
MaxPlanar.opt: ../../pigale/incl/TAXI/DFSGraph.h
MaxPlanar.opt: ../../pigale/incl/TAXI/graphs.h
MaxPlanar.opt: ../../pigale/incl/TAXI/Tpoint.h
more.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tbase.h
more.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tdebug.h
more.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tprop.h
more.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
more.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/propdef.h
more.opt: ../../pigale/incl/TAXI/Tpoint.h
netcut.opt: ../../pigale/incl/TAXI/netcut.h ../../pigale/incl/TAXI/graphs.h
netcut.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graph.h
netcut.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
netcut.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
netcut.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
netcut.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
netcut.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/embedrn.h
netcut.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tmessage.h
NewPolar.opt: ../../pigale/incl/TAXI/Dos.h ../../pigale/incl/TAXI/graphs.h
NewPolar.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graph.h
NewPolar.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
NewPolar.opt: ../../pigale/incl/TAXI/Tsvector.h
NewPolar.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
NewPolar.opt: ../../pigale/incl/TAXI/Tpropio.h
NewPolar.opt: ../../pigale/incl/TAXI/Tstring.h
NewPolar.opt: ../../pigale/incl/TAXI/propdef.h
NewPolar.opt: ../../pigale/incl/TAXI/Tpoint.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tbase.h
NpBiconnect.opt: ../../pigale/incl/TAXI/graphs.h
NpBiconnect.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tprop.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tsvector.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tdebug.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Errors.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tpropio.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tstring.h
NpBiconnect.opt: ../../pigale/incl/TAXI/propdef.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tpoint.h
NpBiconnect.opt: ../../pigale/incl/TAXI/Tmessage.h
NpBiconnect.opt: ../../pigale/incl/TAXI/color.h
Planar.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Planar.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tprop.h
Planar.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Planar.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Planar.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Planar.opt: ../../pigale/incl/TAXI/bicon.h ../../pigale/incl/TAXI/lralgo.h
Planar.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tpoint.h
Planar.opt: ../../pigale/incl/TAXI/DFSGraph.h ../../pigale/incl/TAXI/color.h
Planar.opt: ../../pigale/incl/TAXI/embed.h ../../pigale/incl/TAXI/DFSLow.h
Planar.opt: ../../pigale/incl/TAXI/ndfs.h ../../pigale/incl/TAXI/Tmessage.h
PropTgf.opt: ../../pigale/incl/TAXI/Tproptgf.h ../../pigale/incl/TAXI/Tprop.h
PropTgf.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tsvector.h
PropTgf.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tdebug.h
PropTgf.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
PropTgf.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/Tgf.h
PropTgf.opt: ../../pigale/incl/TAXI/Tpoint.h
PSet.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tbase.h
PSet.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/elmt.h
PSet.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
PSet.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
random.opt: ../../pigale/incl/TAXI/Tbase.h
reduce.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/Tbase.h
reduce.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
reduce.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
reduce.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
reduce.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
reduce.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
reduce.opt: ../../pigale/incl/TAXI/Tmessage.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tbase.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tmessage.h
SchaefferGen.opt: ../../pigale/incl/TAXI/graphs.h
SchaefferGen.opt: ../../pigale/incl/TAXI/graph.h
SchaefferGen.opt: ../../pigale/incl/TAXI/elmt.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tprop.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tsvector.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tdebug.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Errors.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tpropio.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tstring.h
SchaefferGen.opt: ../../pigale/incl/TAXI/propdef.h
SchaefferGen.opt: ../../pigale/incl/TAXI/Tpoint.h
SchaefferGen.opt: ../../pigale/incl/TAXI/color.h
SchaefferGen.opt: ../../pigale/incl/TAXI/random.h
Schnyder.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/SchPack.h
Schnyder.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Schnyder.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Schnyder.opt: ../../pigale/incl/TAXI/Tsvector.h
Schnyder.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Schnyder.opt: ../../pigale/incl/TAXI/Tpropio.h
Schnyder.opt: ../../pigale/incl/TAXI/Tstring.h
Schnyder.opt: ../../pigale/incl/TAXI/propdef.h
Schnyder.opt: ../../pigale/incl/TAXI/Tpoint.h
Schnyder.opt: ../../pigale/incl/TAXI/IntList.h
Schnyder.opt: ../../pigale/incl/TAXI/Tmessage.h
Schnyder.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/embedrn.h
SchnyderWood.opt: ../../pigale/incl/TAXI/SchnyderWood.h
SchnyderWood.opt: ../../pigale/incl/TAXI/graphs.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tbase.h
SchnyderWood.opt: ../../pigale/incl/TAXI/graph.h
SchnyderWood.opt: ../../pigale/incl/TAXI/elmt.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tprop.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tsvector.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tdebug.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Errors.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tpropio.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tstring.h
SchnyderWood.opt: ../../pigale/incl/TAXI/propdef.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tpoint.h
SchnyderWood.opt: ../../pigale/incl/TAXI/IntList.h
SchnyderWood.opt: ../../pigale/incl/TAXI/color.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tmessage.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tflist.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tstack.h
SchnyderWood.opt: ../../pigale/incl/TAXI/Tarray.h
SchnyderWood.opt: ../../pigale/incl/TAXI/KantShel.h
STList.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/Tbase.h
STList.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
STList.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
STList.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
STList.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
STList.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
STList.opt: ../../pigale/incl/TAXI/Tmessage.h
Tgf.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tgf.h
TopoAlgs.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/Tbase.h
TopoAlgs.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
TopoAlgs.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
TopoAlgs.opt: ../../pigale/incl/TAXI/Tsvector.h
TopoAlgs.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
TopoAlgs.opt: ../../pigale/incl/TAXI/Tpropio.h
TopoAlgs.opt: ../../pigale/incl/TAXI/propdef.h
TopoAlgs.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/bicon.h
TopoAlgs.opt: ../../pigale/incl/TAXI/Tmessage.h
TopoAlgs.opt: ../../pigale/incl/TAXI/color.h
Twit.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Tbase.h
Twit.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/lralgo.h
Twit.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Twit.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
Twit.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
Twit.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/graphs.h
Twit.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/DFSGraph.h
Twit.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/bicon.h
VertexPacking.opt: ../../pigale/incl/TAXI/SchPack.h
VertexPacking.opt: ../../pigale/incl/TAXI/graphs.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tbase.h
VertexPacking.opt: ../../pigale/incl/TAXI/graph.h
VertexPacking.opt: ../../pigale/incl/TAXI/elmt.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tprop.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tsvector.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tdebug.h
VertexPacking.opt: ../../pigale/incl/TAXI/Errors.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tpropio.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tstring.h
VertexPacking.opt: ../../pigale/incl/TAXI/propdef.h
VertexPacking.opt: ../../pigale/incl/TAXI/Tpoint.h
VertexPacking.opt: ../../pigale/incl/TAXI/IntList.h
Vision.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graphs.h
Vision.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Vision.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
Vision.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Vision.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
Vision.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
Vision.opt: ../../pigale/incl/TAXI/Tmessage.h ../../pigale/incl/TAXI/color.h
Vision.opt: ../../pigale/incl/TAXI/MaxPath.h ../../pigale/incl/TAXI/Channel.h
