####################### MAY NEED EDITING ########################
#Compiler options
CC=g++
#CPU="-mcpu=i686"
#CPU=-m686 
CPU=
OPT=opt
#PIC if wanted shared dynamic libraries
PIC=-fpic

#Unix libraries to be linked (system dependent)
#UNIXLIB =  -L$(MQTDIR)/lib -lqt-mt -L/usr/X11R6/lib -lglut -lGL -lGLU  
UNIXLIB = -L/usr/X11R6/lib -lX11
AWK=awk
####################### END EDITING #########################
PIGALEPATH=..
SAMPLING =
RAN = ranlib
#SAMPLING = -lc_p
L = tgraph
#GENERAL OPTIONS
.SUFFIXES:.cpp .c .opt .dbg .o 
IFLAGS = -I$(PIGALEPATH)/incl 

#OPTIMIZED OPTIONS
CFLAGSopt = -O3   $(PIC) $(CPU)
CFLAGSopt += -Wall -Wpointer-arith -Werror -pipe
CFLAGSopt +=  -fomit-frame-pointer

#DEBUGGING OPTIONS (-pg -a for sampling)
CFLAGSdbg  =  -g -Wall -Wpointer-arith -Werror -pipe $(PIC) $(CPU)
CFLAGSdbg +=  -DTDEBUG

DLIB    = $(PIGALEPATH)/lib/lib$L$(OPT).so
LIBS    = -L$(PIGALEPATH)/lib -ltgraph$(OPT)
CFLAGS  = $(CFLAGS$(OPT))
VPATH   = ./.obj
FILES   :=  $(wildcard *.cpp)
SPECIAL := PropName.cpp
FILES   := $(filter-out $(SPECIAL), $(FILES))
FILES2  := $(FILES)
FILES2  += $(SPECIAL)
OBJECTS =  $(patsubst %.cpp,%.$(OPT), $(FILES2))
OBJ =  $(patsubst %.$(OPT),$(VPATH)/%.$(OPT), $(OBJECTS))

all : md $(DLIB)

PropName.cpp : $(PIGALEPATH)/incl/TAXI/propdef.h
	$(AWK) -f propname.awk $(PIGALEPATH)/incl/TAXI/propdef.h > PropName.cpp

.cpp.$(OPT): $*.cpp 
	$(CC) -c $(CFLAGS) $(IFLAGS) -o  $(VPATH)/$*.$(OPT)   $*.cpp

$(DLIB):	 $(OBJECTS)
	@rm -f $(PIGALEPATH)/lib/lib$L$(OPT).so
	$(CC) -shared  -o $(PIGALEPATH)/lib/lib$L$(OPT).so  $(OBJ)

clean:
	@rm -f *~ *bak *.flc $(OBJ) *.flc $(DLIB)

depend:
	@makedepend -o.$(OPT) -f gnumakefile $(IFLAGS)  -Y $(FILES) 2> /dev/null

nodepend:
	@makedepend -o.$(OPT) -f gnumakefile  -Y  2> /dev/null

list:
	../makelist *.cpp >Make.lst
	
md:
	@if ! test -d .obj ; then mkdir .obj ; fi
	@if ! test -d ../lib ; then mkdir ../lib ; fi	
	
static:$(OBJECTS)
	@ar cru $(PIGALEPATH)/lib/lib$L$(OPT).la  $(OBJ)
	@ranlib $(PIGALEPATH)/lib/lib$L$(OPT).la
		
test:
	@echo OBJ=$(OBJ)
	@echo OBJECTS=$(OBJECTS)

.PHONY: md all
# DO NOT DELETE

3-ConOrientTriang.opt: ../incl/TAXI/KantShel.h ../incl/TAXI/graphs.h
3-ConOrientTriang.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
3-ConOrientTriang.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
3-ConOrientTriang.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
3-ConOrientTriang.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
3-ConOrientTriang.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
3-ConOrientTriang.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/IntList.h
3-ConOrientTriang.opt: ../incl/TAXI/Tflist.h ../incl/TAXI/Tstack.h
3-ConOrientTriang.opt: ../incl/TAXI/Tarray.h
3-ConShelling1.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/graphs.h
3-ConShelling1.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
3-ConShelling1.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
3-ConShelling1.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
3-ConShelling1.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
3-ConShelling1.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
3-ConShelling1.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/color.h
3-ConShelling1.opt: ../incl/TAXI/KantShel.h ../incl/TAXI/IntList.h
3-ConShelling2.opt: ../incl/TAXI/KantShel.h ../incl/TAXI/graphs.h
3-ConShelling2.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
3-ConShelling2.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
3-ConShelling2.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
3-ConShelling2.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
3-ConShelling2.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
3-ConShelling2.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/IntList.h
3-ConShelling2.opt: ../incl/TAXI/color.h ../incl/TAXI/Tmessage.h
3-ConShelling2.opt: ../incl/TAXI/Tflist.h ../incl/TAXI/Tstack.h
3-ConShelling2.opt: ../incl/TAXI/Tarray.h
Barycenter.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
Barycenter.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
Barycenter.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
Barycenter.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
Barycenter.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
Barycenter.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/Tmessage.h
Barycenter.opt: ../incl/TAXI/smatrix.h
BFS.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
BFS.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
BFS.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
BFS.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
BFS.opt: ../incl/TAXI/Tsmap.h
Biconnect.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/color.h
Biconnect.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
Biconnect.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Biconnect.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Biconnect.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Biconnect.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
Biconnect.opt: ../incl/TAXI/IntList.h
Bipolar.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
Bipolar.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Bipolar.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Bipolar.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Bipolar.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
Bipolar.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/color.h
Bipolar.opt: ../incl/TAXI/DFSGraph.h
BipPlanarize.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h
BipPlanarize.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
BipPlanarize.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
BipPlanarize.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
BipPlanarize.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
BipPlanarize.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
BipPlanarize.opt: ../incl/TAXI/color.h ../incl/TAXI/Tmessage.h
CotreeCritical.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/CotreeCritical.h
CotreeCritical.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/color.h
CotreeCritical.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
CotreeCritical.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
CotreeCritical.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
CotreeCritical.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
CotreeCritical.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
CotreeCritical.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/Tmessage.h
CotreeCritical.opt: ../incl/TAXI/DFSLow.h ../incl/TAXI/lralgo.h
CotreeCritical.opt: ../incl/TAXI/bicon.h
Debug.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Debug.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
Debug.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Debug.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Debug.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
DFS.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
DFS.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
DFS.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
DFS.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
DFS.opt: ../incl/TAXI/bicon.h ../incl/TAXI/color.h
DFSGraph.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/DFSLow.h ../incl/TAXI/color.h
DFSGraph.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/graphs.h
DFSGraph.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
DFSGraph.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
DFSGraph.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
DFSGraph.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
DFSGraph.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/lralgo.h
DFSGraph.opt: ../incl/TAXI/bicon.h
DFSMap.opt: ../incl/TAXI/DFSLow.h ../incl/TAXI/Tbase.h ../incl/TAXI/color.h
DFSMap.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/graphs.h
DFSMap.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
DFSMap.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
DFSMap.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
DFSMap.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
DFSMap.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/lralgo.h ../incl/TAXI/bicon.h
DFSMap.opt: ../incl/TAXI/embed.h
Diagonalise.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tdebug.h
Diagonalise.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tmessage.h
Diagonalise.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
Diagonalise.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
Diagonalise.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tpropio.h
Diagonalise.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
Diagonalise.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/netcut.h
Diagonalise.opt: ../incl/TAXI/embedrn.h
Embed2Pages.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
Embed2Pages.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
Embed2Pages.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Embed2Pages.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Embed2Pages.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Embed2Pages.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
Embed2Pages.opt: ../incl/TAXI/IntList.h ../incl/TAXI/Tmessage.h
Embed2Pages.opt: ../incl/TAXI/color.h
EmbedCCD.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
EmbedCCD.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
EmbedCCD.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
EmbedCCD.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
EmbedCCD.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
EmbedCCD.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/SchnyderWood.h
EmbedCCD.opt: ../incl/TAXI/IntList.h ../incl/TAXI/color.h
EmbedCCD.opt: ../incl/TAXI/Tstack.h ../incl/TAXI/Tarray.h
EmbedFPP.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
EmbedFPP.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
EmbedFPP.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
EmbedFPP.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
EmbedFPP.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
EmbedFPP.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/SchPack.h
EmbedFPP.opt: ../incl/TAXI/IntList.h ../incl/TAXI/MaxPath.h
EmbedPolrec.opt: ../incl/Pigale.h ../incl/TAXI/Tbase.h
EmbedPolrec.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/graphs.h
EmbedPolrec.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
EmbedPolrec.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
EmbedPolrec.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
EmbedPolrec.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
EmbedPolrec.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
EmbedPolrec.opt: ../incl/TAXI/color.h ../incl/TAXI/Tfile.h
EmbedPolrec.opt: ../incl/TAXI/random.h ../incl/TAXI/MaxPath.h
EmbedPolyline.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
EmbedPolyline.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
EmbedPolyline.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
EmbedPolyline.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
EmbedPolyline.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
EmbedPolyline.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
EmbedPolyline.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/MaxPath.h
EmbedPolyline.opt: ../incl/TAXI/color.h ../incl/TAXI/SchPack.h
EmbedPolyline.opt: ../incl/TAXI/IntList.h
EmbedTutteCircle.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
EmbedTutteCircle.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
EmbedTutteCircle.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
EmbedTutteCircle.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
EmbedTutteCircle.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
EmbedTutteCircle.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
EmbedTutteCircle.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/color.h
EmbedVision.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
EmbedVision.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
EmbedVision.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
EmbedVision.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
EmbedVision.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
EmbedVision.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
EmbedVision.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/MaxPath.h
EmbedVision.opt: ../incl/TAXI/color.h
FastTwit.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/lralgo.h ../incl/TAXI/graph.h
FastTwit.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
FastTwit.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
FastTwit.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
FastTwit.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
FastTwit.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tpoint.h
FastTwit.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/color.h
FastTwit.opt: ../incl/TAXI/bicon.h
File.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tstring.h ../incl/TAXI/graph.h
File.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
File.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
File.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h ../incl/TAXI/Tgf.h
File.opt: ../incl/TAXI/Tproptgf.h ../incl/TAXI/Tfile.h ../incl/TAXI/graphs.h
File.opt: ../incl/TAXI/Tsmap.h ../incl/TAXI/color.h ../incl/TAXI/Tmessage.h
Generate.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/Tbase.h
Generate.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Generate.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
Generate.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Generate.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Generate.opt: ../incl/TAXI/propdef.h ../incl/TAXI/random.h
Generate.opt: ../incl/TAXI/Tstack.h ../incl/TAXI/Tarray.h
GeoAlgs.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/smatrix.h
GeoAlgs.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/elmt.h
GeoAlgs.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
GeoAlgs.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/Tpoint.h
GeoAlgs.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h ../incl/TAXI/Tprop.h
GeoAlgs.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/propdef.h
GeoAlgs.opt: ../incl/TAXI/color.h
Graph.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tpoint.h ../incl/TAXI/graphs.h
Graph.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
Graph.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
Graph.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
Graph.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h ../incl/TAXI/bicon.h
Graph.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/color.h
k-InfOrient.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
k-InfOrient.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
k-InfOrient.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
k-InfOrient.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
k-InfOrient.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
k-InfOrient.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
k-InfOrient.opt: ../incl/TAXI/IntList.h
LR-Algo.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
LR-Algo.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
LR-Algo.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
LR-Algo.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
LR-Algo.opt: ../incl/TAXI/propdef.h ../incl/TAXI/graphs.h
LR-Algo.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/bicon.h ../incl/TAXI/lralgo.h
LR-Algo.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/color.h
LR-Map.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tbase.h
LR-Map.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
LR-Map.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
LR-Map.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
LR-Map.opt: ../incl/TAXI/propdef.h ../incl/TAXI/graphs.h
LR-Map.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/bicon.h ../incl/TAXI/lralgo.h
LR-Map.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/color.h ../incl/TAXI/embed.h
LR-Map.opt: ../incl/TAXI/DFSLow.h ../incl/TAXI/Tmessage.h
mark.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
mark.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
mark.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
mark.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
mark.opt: ../incl/TAXI/bicon.h ../incl/TAXI/Tmessage.h
MaxPlanar.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tbase.h
MaxPlanar.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
MaxPlanar.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
MaxPlanar.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
MaxPlanar.opt: ../incl/TAXI/propdef.h ../incl/TAXI/color.h
MaxPlanar.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/graphs.h
MaxPlanar.opt: ../incl/TAXI/Tpoint.h
more.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tbase.h ../incl/TAXI/elmt.h
more.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h ../incl/TAXI/Tprop.h
more.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h ../incl/TAXI/graph.h
more.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
netcut.opt: ../incl/TAXI/netcut.h ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h
netcut.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
netcut.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
netcut.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
netcut.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
netcut.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/Tmessage.h
netcut.opt: ../incl/TAXI/embedrn.h ../incl/TAXI/color.h
NewPolar.opt: ../incl/TAXI/Dos.h ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h
NewPolar.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
NewPolar.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
NewPolar.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
NewPolar.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
NewPolar.opt: ../incl/TAXI/Tpoint.h
NpBiconnect.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
NpBiconnect.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
NpBiconnect.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
NpBiconnect.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
NpBiconnect.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
NpBiconnect.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
NpBiconnect.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/color.h
Planar.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tbase.h
Planar.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Planar.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Planar.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Planar.opt: ../incl/TAXI/propdef.h ../incl/TAXI/bicon.h ../incl/TAXI/lralgo.h
Planar.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tpoint.h
Planar.opt: ../incl/TAXI/DFSGraph.h ../incl/TAXI/color.h ../incl/TAXI/embed.h
Planar.opt: ../incl/TAXI/DFSLow.h ../incl/TAXI/ndfs.h ../incl/TAXI/Tmessage.h
PropTgf.opt: ../incl/TAXI/Tproptgf.h ../incl/TAXI/Tprop.h
PropTgf.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tsvector.h ../incl/TAXI/elmt.h
PropTgf.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
PropTgf.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h ../incl/TAXI/Tgf.h
PropTgf.opt: ../incl/TAXI/Tpoint.h
PSet.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tbase.h ../incl/TAXI/Tsvector.h
PSet.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
PSet.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
random.opt: ../incl/TAXI/Tbase.h
reduce.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h
reduce.opt: ../incl/TAXI/graph.h ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
reduce.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
reduce.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
reduce.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
reduce.opt: ../incl/TAXI/Tmessage.h
SchaefferGen.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tmessage.h
SchaefferGen.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
SchaefferGen.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
SchaefferGen.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
SchaefferGen.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
SchaefferGen.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
SchaefferGen.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/color.h
SchaefferGen.opt: ../incl/TAXI/random.h
Schnyder.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/SchPack.h
Schnyder.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
Schnyder.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Schnyder.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Schnyder.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Schnyder.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
Schnyder.opt: ../incl/TAXI/IntList.h ../incl/TAXI/Tmessage.h
Schnyder.opt: ../incl/TAXI/color.h ../incl/TAXI/embedrn.h
SchnyderWood.opt: ../incl/TAXI/SchnyderWood.h ../incl/TAXI/graphs.h
SchnyderWood.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
SchnyderWood.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
SchnyderWood.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
SchnyderWood.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
SchnyderWood.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
SchnyderWood.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/IntList.h
SchnyderWood.opt: ../incl/TAXI/color.h ../incl/TAXI/Tmessage.h
SchnyderWood.opt: ../incl/TAXI/Tflist.h ../incl/TAXI/Tstack.h
SchnyderWood.opt: ../incl/TAXI/Tarray.h ../incl/TAXI/KantShel.h
SchnyderWood.opt: ../incl/TAXI/SWShelling.h
STList.opt: ../incl/TAXI/graphs.h ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
STList.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
STList.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
STList.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
STList.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
STList.opt: ../incl/TAXI/Tmessage.h
SWShelling.opt: ../incl/TAXI/SWShelling.h ../incl/TAXI/graphs.h
SWShelling.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
SWShelling.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
SWShelling.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
SWShelling.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
SWShelling.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
SWShelling.opt: ../incl/TAXI/IntList.h ../incl/TAXI/color.h
SWShelling.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/Tflist.h
SWShelling.opt: ../incl/TAXI/Tstack.h ../incl/TAXI/Tarray.h
Tgf.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/Tgf.h ../incl/TAXI/Tsvector.h
Tgf.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
TopoAlgs.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/Tbase.h
TopoAlgs.opt: ../incl/TAXI/graphs.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
TopoAlgs.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
TopoAlgs.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
TopoAlgs.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/propdef.h
TopoAlgs.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/bicon.h
TopoAlgs.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/color.h
Twit.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Tbase.h ../incl/TAXI/Errors.h
Twit.opt: ../incl/TAXI/lralgo.h ../incl/TAXI/graph.h ../incl/TAXI/elmt.h
Twit.opt: ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h ../incl/TAXI/Tpropio.h
Twit.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h ../incl/TAXI/graphs.h
Twit.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/DFSGraph.h ../incl/TAXI/color.h
Twit.opt: ../incl/TAXI/bicon.h
VertexPacking.opt: ../incl/TAXI/SchPack.h ../incl/TAXI/graphs.h
VertexPacking.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graph.h
VertexPacking.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h
VertexPacking.opt: ../incl/TAXI/Tsvector.h ../incl/TAXI/Tdebug.h
VertexPacking.opt: ../incl/TAXI/Errors.h ../incl/TAXI/Tpropio.h
VertexPacking.opt: ../incl/TAXI/Tstring.h ../incl/TAXI/propdef.h
VertexPacking.opt: ../incl/TAXI/Tpoint.h ../incl/TAXI/IntList.h
Vision.opt: ../incl/TAXI/Tbase.h ../incl/TAXI/graphs.h ../incl/TAXI/graph.h
Vision.opt: ../incl/TAXI/elmt.h ../incl/TAXI/Tprop.h ../incl/TAXI/Tsvector.h
Vision.opt: ../incl/TAXI/Tdebug.h ../incl/TAXI/Errors.h
Vision.opt: ../incl/TAXI/Tpropio.h ../incl/TAXI/Tstring.h
Vision.opt: ../incl/TAXI/propdef.h ../incl/TAXI/Tpoint.h
Vision.opt: ../incl/TAXI/Tmessage.h ../incl/TAXI/color.h
Vision.opt: ../incl/TAXI/MaxPath.h ../incl/TAXI/Channel.h
