/* incl/config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */


#ifndef _CONFIG_H
#define _CONFIG_H


/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <GL/glut.h> header file. */
#define HAVE_GL_GLUT_H 1

/* Define to 1 if you have the <GL/gl.h> header file. */
#define HAVE_GL_GL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `GL' library (-lGL). */
#define HAVE_LIBGL 1

/* Define to 1 if you have the `GLU' library (-lGLU). */
#define HAVE_LIBGLU 1

/* Define to 1 if you have the `glut' library (-lglut). */
#define HAVE_LIBGLUT 1

/* Define to 1 if you have the `Xi' library (-lXi). */
#define HAVE_LIBXI 1

/* Define to 1 if you have the `Xmu' library (-lXmu). */
#define HAVE_LIBXMU 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "pigale"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "hf@sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pigale"

/* Path to Pigale root directory */
#define PACKAGE_PATH "/home/pigale"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pigale 1.2.14"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "Public Implementation of a Graph Library and Editor"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2.14"

/* Qt Thread Support */
#define QT_THREAD_SUPPORT 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.2.14"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

#endif
