####################### MAY NEED EDITING ########################
#Compiler options
CC=g++
#CPU="-mcpu=i686"
CPU=
#OPT: if set to dbg > debug version
#OPT: if set to opt > optimised version
OPT=opt
#PIC if wanted shared dynamic libraries
PIC=-fpic
#libray paths
MQTDIR=$(QTDIR)
UNIXLIB =  -L$(MQTDIR)/lib -lqt-mt -L/usr/X11R6/lib -lglut -lGL -lGLU  
#include paths
IFLAGS =  -I$(MQTDIR)/include 
IFLAGS += -I$(PIGALEPATH)/incl
#awk 
AWK=awk
####################### END EDITING #########################
PIGALEPATH=../../pigale
NVERSION=BETA
# P = name of output program
ifeq ($(OPT),opt)
P=Pigale
else
P=Pigale_dbg
endif

# L = name of libray
L=pigaleQt
MMOC=$(MQTDIR)/bin/moc
PIGALELIB =  -L$(PIGALEPATH)/lib    -l$(L)$(OPT) -ltgraph$(OPT)

#GENERAL OPTIONS
.SUFFIXES:.cpp .o
#OPTIMIZED OPTIONS
CFLAGSopt = -O3  $(PIC) $(CPU)
CFLAGSopt +=  -Wall -Wstrict-prototypes -Wpointer-arith -Werror  -pipe
CFLAGSopt +=  -fomit-frame-pointer 
CFLAGSopt +=  -DQT -DVERSION_$(NVERSION) 
CFLAGSopt +=  -DQT_THREAD_SUPPORT 

#DEBUGGING OPTIONS
CFLAGSdbg  =  -g -Wall $(PIC) $(CPU)
CFLAGSdbg +=  -Wstrict-prototypes -Wpointer-arith -Werror -pipe
CFLAGSdbg +=  -DTDEBUG
CFLAGSdbg +=  -DQT -DVERSION_$(NVERSION)
CFLAGSdbg +=  -DQT_THREAD_SUPPORT 

CFLAGS  = $(CFLAGS$(OPT))
VPATH   = $(PIGALEPATH)/tmp.$(OPT)
DLIB    = $(PIGALEPATH)/lib/lib$L$(OPT).so
FILEALL := $(wildcard *.cpp)
FILES   := $(filter-out client.cpp, $(FILEALL))
INCLALL := $(wildcard *.h)
INCL    := $(filter-out client.h, $(INCLALL))
MOC_CPP := $(patsubst %.h,moc_%.cpp, $(INCL))
FILES_WO_MOC := $(filter-out $(MOC_CPP), $(FILES))
FILES_W_MOC  := $(FILES_WO_MOC)
FILES_W_MOC  += $(MOC_CPP)
OBJECTS       =  $(patsubst %.cpp,%.o, $(FILES_W_MOC))
OBJ           =  $(patsubst %.cpp,$(VPATH)/%.o, $(FILES_W_MOC))
ALLOBJ        = $(wildcard $(VPATH)/*.o)

all : $(P)

$(PIGALEPATH)/incl/QT/Action.h:$(PIGALEPATH)/incl/QT/Action_def.h
	$(AWK) -f Action.awk $(PIGALEPATH)/incl/QT/Action_def.h > $(PIGALEPATH)/incl/QT/Action.h
 
#moc_%.cpp:%.h
#	$(MMOC) $< -o $@

.cpp.o: $*.cpp
	$(CC) -c $(CFLAGS) $(IFLAGS) -o  $(VPATH)/$*.o   $*.cpp
	
$(DLIB):$(OBJECTS) 
	@rm -f $(PIGALEPATH)/lib/lib$L$(OPT).so
	@$(CC) -shared  -o $(PIGALEPATH)/lib/lib$L$(OPT).so  $(OBJ)

$(P) :$(DLIB) $(PIGALEPATH)/lib/libtgraph$(OPT).so 
	$(CC)  $(CFLAGS) -o $(P)  $(PIGALELIB)  $(UNIXLIB) 

clean:
	@rm -f *~ *bak *.flc  moc_*.cpp  $(OBJ) $(DLIB)

test:
	@echo OBJ=$(OBJ)
	@echo OBJECTS=$(OBJECTS)
	@echo FILES=$(FILES)
	
static:$(DLIB) $(PIGALEPATH)/lib/libtgraph$(OPT).so 
	g++  $(CFLAGS) -o s$(P) $(ALLOBJ)  $(UNIXLIB) 

moc_cpp:    $(MOC_CPP)

depend:
	@makedepend -o.o  -fgnumakefile -I$(PIGALEPATH)/incl  -Y   $(FILES_WO_MOC)  2> /dev/null

nodepend:
	@makedepend -o.o  -fgnumakefile -Y    2> /dev/null

# DO NOT DELETE

CanvasGrid.o: pigaleWindow.h ../../pigale/incl/Pigale.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tbase.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tmessage.h
CanvasGrid.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
CanvasGrid.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tsvector.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tpropio.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tstring.h
CanvasGrid.o: ../../pigale/incl/TAXI/propdef.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
CanvasGrid.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
CanvasGrid.o: GraphWidget.h ../../pigale/incl/QT/pigaleQcolors.h
CanvasGrid.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/pigaleCanvas.h
CanvasGrid.o: ../../pigale/incl/QT/grid.h
CanvasGrid.o: ../../pigale/incl/QT/GraphWidgetPrivate.h mouse_actions.h
CanvasGrid.o: gprop.h
CanvasItem.o: pigaleWindow.h ../../pigale/incl/Pigale.h
CanvasItem.o: ../../pigale/incl/TAXI/Tbase.h
CanvasItem.o: ../../pigale/incl/TAXI/Tmessage.h
CanvasItem.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
CanvasItem.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
CanvasItem.o: ../../pigale/incl/TAXI/Tsvector.h
CanvasItem.o: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
CanvasItem.o: ../../pigale/incl/TAXI/Tpropio.h
CanvasItem.o: ../../pigale/incl/TAXI/Tstring.h
CanvasItem.o: ../../pigale/incl/TAXI/propdef.h
CanvasItem.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
CanvasItem.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
CanvasItem.o: GraphWidget.h mouse_actions.h
CanvasItem.o: ../../pigale/incl/QT/pigaleQcolors.h
CanvasItem.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/pigaleCanvas.h
CanvasItem.o: ../../pigale/incl/QT/grid.h
CanvasItem.o: ../../pigale/incl/QT/GraphWidgetPrivate.h
CanvasSpring.o: pigaleWindow.h ../../pigale/incl/Pigale.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tbase.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tmessage.h
CanvasSpring.o: ../../pigale/incl/TAXI/graphs.h
CanvasSpring.o: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tprop.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tsvector.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tdebug.h
CanvasSpring.o: ../../pigale/incl/TAXI/Errors.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tpropio.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tstring.h
CanvasSpring.o: ../../pigale/incl/TAXI/propdef.h
CanvasSpring.o: ../../pigale/incl/TAXI/Tpoint.h
CanvasSpring.o: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
CanvasSpring.o: ../../pigale/incl/TAXI/random.h GraphWidget.h mouse_actions.h
CanvasSpring.o: gprop.h ../../pigale/incl/QT/pigaleQcolors.h
CanvasSpring.o: ../../pigale/incl/QT/Misc.h
CanvasSpring.o: ../../pigale/incl/QT/pigaleCanvas.h
CanvasSpring.o: ../../pigale/incl/QT/grid.h
CanvasSpring.o: ../../pigale/incl/QT/GraphWidgetPrivate.h
ClientSocket.o: ClientSocket.h ../../pigale/incl/config.h
ClientSocket.o: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
ClientSocket.o: ../../pigale/incl/TAXI/Tmessage.h
ClientSocket.o: ../../pigale/incl/TAXI/graphs.h
ClientSocket.o: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
ClientSocket.o: ../../pigale/incl/TAXI/Tprop.h
ClientSocket.o: ../../pigale/incl/TAXI/Tsvector.h
ClientSocket.o: ../../pigale/incl/TAXI/Tdebug.h
ClientSocket.o: ../../pigale/incl/TAXI/Errors.h
ClientSocket.o: ../../pigale/incl/TAXI/Tpropio.h
ClientSocket.o: ../../pigale/incl/TAXI/Tstring.h
ClientSocket.o: ../../pigale/incl/TAXI/propdef.h
ClientSocket.o: ../../pigale/incl/TAXI/Tpoint.h
ClientSocket.o: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
ClientSocket.o: ../../pigale/incl/TAXI/random.h pigaleWindow.h
ClientSocket.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Action_def.h
ClientSocket.o: GraphWidget.h GraphGL.h GraphSym.h mouse_actions.h gprop.h
ClientSocket.o: LineEditNum.h ../../pigale/incl/QT/Handler.h
ClientSocket.o: ../../pigale/incl/QT/pigalePaint.h
ClientSocket.o: ../../pigale/incl/QT/pigaleCanvas.h
ClientSocket.o: ../../pigale/incl/QT/grid.h
EmbedCurves.o: pigaleWindow.h ../../pigale/incl/Pigale.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tbase.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tmessage.h
EmbedCurves.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
EmbedCurves.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tsvector.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tdebug.h
EmbedCurves.o: ../../pigale/incl/TAXI/Errors.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tpropio.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tstring.h
EmbedCurves.o: ../../pigale/incl/TAXI/propdef.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
EmbedCurves.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
EmbedCurves.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Action_def.h
EmbedCurves.o: GraphWidget.h ../../pigale/incl/QT/pigaleCanvas.h
EmbedCurves.o: ../../pigale/incl/QT/grid.h
EmbedCurves.o: ../../pigale/incl/QT/GraphWidgetPrivate.h
glcontrolwidget.o: ../../pigale/incl/TAXI/Tbase.h glcontrolwidget.h
gprop.o: gprop.h pigaleWindow.h ../../pigale/incl/Pigale.h
gprop.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
gprop.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
gprop.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
gprop.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
gprop.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
gprop.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
gprop.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
gprop.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
gprop.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Action_def.h
GraphGL.o: pigaleWindow.h ../../pigale/incl/Pigale.h
GraphGL.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
GraphGL.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
GraphGL.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
GraphGL.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
GraphGL.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
GraphGL.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
GraphGL.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
GraphGL.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
GraphGL.o: GraphGL.h glcontrolwidget.h mouse_actions.h
GraphGL.o: ../../pigale/incl/QT/GLWindow.h ../../pigale/incl/QT/Misc.h
GraphGL.o: ../../pigale/incl/QT/pigaleQcolors.h
GraphGL.o: ../../pigale/incl/TAXI/netcut.h ../../pigale/incl/TAXI/embedrn.h
GraphGL.o: ../../pigale/incl/config.h
GraphSym.o: pigaleWindow.h ../../pigale/incl/Pigale.h
GraphSym.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
GraphSym.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
GraphSym.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
GraphSym.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
GraphSym.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
GraphSym.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
GraphSym.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
GraphSym.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
GraphSym.o: GraphSym.h ../../pigale/incl/QT/SymWindow.h
GraphSym.o: ../../pigale/incl/QT/pigaleQcolors.h ../../pigale/incl/QT/Misc.h
Handler.o: ../../pigale/incl/QT/Handler.h ../../pigale/incl/QT/Action_def.h
Handler.o: pigaleWindow.h ../../pigale/incl/Pigale.h
Handler.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
Handler.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Handler.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Handler.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Handler.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Handler.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Handler.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
Handler.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
Handler.o: ../../pigale/incl/QT/Misc.h
LineEditNum.o: LineEditNum.h
Macro.o: pigaleWindow.h ../../pigale/incl/Pigale.h
Macro.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
Macro.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Macro.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Macro.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Macro.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Macro.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Macro.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
Macro.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
Macro.o: GraphWidget.h mouse_actions.h LineEditNum.h
Macro.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Action_def.h
Macro.o: ../../pigale/incl/TAXI/Tgf.h
main.o: ../../pigale/incl/config.h pigaleWindow.h ../../pigale/incl/Pigale.h
main.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
main.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
main.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
main.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
main.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
main.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
main.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
main.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
main.o: ../../pigale/incl/QT/Misc.h
MiscQt.o: pigaleWindow.h ../../pigale/incl/Pigale.h
MiscQt.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
MiscQt.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
MiscQt.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
MiscQt.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
MiscQt.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
MiscQt.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
MiscQt.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
MiscQt.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
MiscQt.o: GraphWidget.h
mouse_actions.o: mouse_actions.h GraphWidget.h GraphGL.h
pigaleCanvas.o: pigaleWindow.h ../../pigale/incl/Pigale.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tbase.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tmessage.h
pigaleCanvas.o: ../../pigale/incl/TAXI/graphs.h
pigaleCanvas.o: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tprop.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tsvector.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tdebug.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Errors.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tpropio.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tstring.h
pigaleCanvas.o: ../../pigale/incl/TAXI/propdef.h
pigaleCanvas.o: ../../pigale/incl/TAXI/Tpoint.h
pigaleCanvas.o: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
pigaleCanvas.o: ../../pigale/incl/TAXI/random.h GraphWidget.h mouse_actions.h
pigaleCanvas.o: gprop.h ../../pigale/incl/QT/pigaleQcolors.h
pigaleCanvas.o: ../../pigale/incl/QT/Misc.h
pigaleCanvas.o: ../../pigale/incl/QT/pigaleCanvas.h
pigaleCanvas.o: ../../pigale/incl/QT/grid.h
pigaleCanvas.o: ../../pigale/incl/QT/GraphWidgetPrivate.h
pigalePaint.o: pigaleWindow.h ../../pigale/incl/Pigale.h
pigalePaint.o: ../../pigale/incl/TAXI/Tbase.h
pigalePaint.o: ../../pigale/incl/TAXI/Tmessage.h
pigalePaint.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
pigalePaint.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
pigalePaint.o: ../../pigale/incl/TAXI/Tsvector.h
pigalePaint.o: ../../pigale/incl/TAXI/Tdebug.h
pigalePaint.o: ../../pigale/incl/TAXI/Errors.h
pigalePaint.o: ../../pigale/incl/TAXI/Tpropio.h
pigalePaint.o: ../../pigale/incl/TAXI/Tstring.h
pigalePaint.o: ../../pigale/incl/TAXI/propdef.h
pigalePaint.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
pigalePaint.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
pigalePaint.o: ../../pigale/incl/QT/pigalePaint.h
pigalePaint.o: ../../pigale/incl/QT/pigaleQcolors.h
pigalePaint.o: ../../pigale/incl/QT/Misc.h
pigaleWindow.o: ../../pigale/incl/config.h pigaleWindow.h
pigaleWindow.o: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tmessage.h
pigaleWindow.o: ../../pigale/incl/TAXI/graphs.h
pigaleWindow.o: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tprop.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tsvector.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tdebug.h
pigaleWindow.o: ../../pigale/incl/TAXI/Errors.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tpropio.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tstring.h
pigaleWindow.o: ../../pigale/incl/TAXI/propdef.h
pigaleWindow.o: ../../pigale/incl/TAXI/Tpoint.h
pigaleWindow.o: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
pigaleWindow.o: ../../pigale/incl/TAXI/random.h ../../pigale/incl/TAXI/Tgf.h
pigaleWindow.o: GraphWidget.h GraphGL.h GraphSym.h mouse_actions.h gprop.h
pigaleWindow.o: LineEditNum.h ../../pigale/incl/QT/pigaleWindow_doc.h
pigaleWindow.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Handler.h
pigaleWindow.o: ../../pigale/incl/QT/Action_def.h
pigaleWindow.o: ../../pigale/incl/QT/Action.h
pigaleWindow.o: ../../pigale/incl/QT/pigalePaint.h
pigaleWindow.o: ../../pigale/incl/QT/pigaleCanvas.h
pigaleWindow.o: ../../pigale/incl/QT/grid.h icones/fileopen.xpm
pigaleWindow.o: icones/filenew.xpm icones/fileprint.xpm icones/filesave.xpm
pigaleWindow.o: icones/info.xpm icones/sleft.xpm icones/sright.xpm
pigaleWindow.o: icones/sreload.xpm icones/help.xpm icones/xman.xpm
pigaleWindow.o: icones/sleftarrow.xpm icones/srightarrow.xpm
pigaleWindow.o: icones/sfilesave.xpm icones/macroplay.xpm icones/film.xpm
Settings.o: ../../pigale/incl/config.h pigaleWindow.h
Settings.o: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
Settings.o: ../../pigale/incl/TAXI/Tmessage.h ../../pigale/incl/TAXI/graphs.h
Settings.o: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
Settings.o: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
Settings.o: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Settings.o: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
Settings.o: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
Settings.o: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
Settings.o: ../../pigale/incl/TAXI/random.h mouse_actions.h LineEditNum.h
Settings.o: gprop.h ../../pigale/incl/QT/Misc.h
Settings.o: ../../pigale/incl/QT/Handler.h
Test.o: pigaleWindow.h ../../pigale/incl/Pigale.h
Test.o: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
Test.o: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Test.o: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Test.o: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Test.o: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Test.o: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Test.o: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
Test.o: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
Test.o: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Action_def.h
Test.o: GraphWidget.h ../../pigale/incl/QT/pigaleCanvas.h
Test.o: ../../pigale/incl/QT/grid.h ../../pigale/incl/QT/GraphWidgetPrivate.h
