####################### MAY NEED EDITING ########################
#Compiler options
CC=g++
#CPU="-mcpu=i686"
CPU=
#OPT: if set to dbg > debug version
#OPT: if set to opt > optimised version
OPT=opt
#PIC if wanted shared dynamic libraries
PIC=-fpic
#libray paths
MQTDIR=$(QTDIR)
UNIXLIB =  -L$(MQTDIR)/lib -lqt-mt -L/usr/X11R6/lib -lglut -lGL -lGLU  
#include paths
IFLAGS =  -I$(MQTDIR)/include 
IFLAGS += -I$(PIGALEPATH)/incl
#awk 
AWK=awk
####################### END EDITING #########################
PIGALEPATH=../../pigale
NVERSION=BETA
# P = name of output program
ifeq ($(OPT),opt)
P=Pigale
else
P=Pigale_dbg
endif

# L = name of libray
L=pigaleQt
MMOC=$(MQTDIR)/bin/moc
PIGALELIB =  -L$(PIGALEPATH)/lib    -l$(L)$(OPT) -ltgraph$(OPT)

#GENERAL OPTIONS
.SUFFIXES:.cpp .o .obj .opt .dbg
#OPTIMIZED OPTIONS
CFLAGSopt = -O3  $(PIC) $(CPU)
#CFLAGSopt +=  -Wall -Wstrict-prototypes -Wpointer-arith  -pipe
CFLAGSopt +=  -Wall -Wstrict-prototypes -Wpointer-arith -Werror  -pipe
CFLAGSopt +=  -fomit-frame-pointer 
CFLAGSopt +=  -DQT -DVERSION_$(NVERSION) 
CFLAGSopt +=  -DQT_THREAD_SUPPORT 

#DEBUGGING OPTIONS
CFLAGSdbg  =  -g -Wall $(PIC) $(CPU)
CFLAGSdbg +=  -Wstrict-prototypes -Wpointer-arith -Werror -pipe
CFLAGSdbg +=  -DTDEBUG
CFLAGSdbg +=  -DQT -DVERSION_$(NVERSION)
CFLAGSdbg +=  -DQT_THREAD_SUPPORT 

CFLAGS  = $(CFLAGS$(OPT))
VPATH   = ./.obj
DLIB    = $(PIGALEPATH)/lib/lib$L$(OPT).so
FILEALL := $(wildcard *.cpp)
FILES   := $(filter-out client.cpp moc_client.cpp, $(FILEALL))
INCLALL := $(wildcard *.h)
INCL    := $(filter-out client.h, $(INCLALL))
MOC_CPP := $(patsubst %.h,moc_%.cpp, $(INCL))
#MOC_CPP := $(filter-out moc_client.cpp, $(MOC_CPP))
FILES_WO_MOC := $(filter-out $(MOC_CPP), $(FILES))
FILES_W_MOC  := $(FILES_WO_MOC)
FILES_W_MOC  += $(MOC_CPP)
OBJECTS       =  $(patsubst %.cpp,%.$(OPT), $(FILES_W_MOC))
OBJ           =  $(patsubst %.cpp,$(VPATH)/%.$(OPT), $(FILES_W_MOC))
ALLOBJ        = $(wildcard $(VPATH)/*.$(OPT))
ALLOBJ        += $(wildcard $(PIGALEPATH)/tgraph/.obj/*.$(OPT))
all : $(P) 

$(PIGALEPATH)/incl/QT/Action.h:$(PIGALEPATH)/incl/QT/Action_def.h
	$(AWK) -f Action.awk $(PIGALEPATH)/incl/QT/Action_def.h > $(PIGALEPATH)/incl/QT/Action.h
 
moc_%.cpp:%.h
	$(MMOC) $< -o $@

.cpp.$(OPT): $*.cpp
	$(CC) -c $(CFLAGS) $(IFLAGS) -o  $(VPATH)/$*.$(OPT)  $*.cpp

$(DLIB):$(OBJECTS) 
	@rm -f $(PIGALEPATH)/lib/lib$L$(OPT).so
	@$(CC) -shared  -o $(PIGALEPATH)/lib/lib$L$(OPT).so  $(OBJ)

$(P) :md $(DLIB) $(PIGALEPATH)/lib/libtgraph$(OPT).so 
	$(CC)  $(CFLAGS) -o $(P)  $(PIGALELIB)  $(UNIXLIB) 
	
clean:
	@rm -f *~ *bak *.flc  moc_*.cpp  $(OBJ) $(DLIB)
	
md: depend
	@if ! test -d .obj ; then mkdir .obj ; fi
test:
	@echo OBJ=$(OBJ)
	@echo OBJECTS=$(OBJECTS)
	@echo FILES=$(FILES)

static:md $(DLIB) $(PIGALEPATH)/lib/libtgraph$(OPT).so 
	g++  $(CFLAGS) -o s$(P) $(ALLOBJ)  $(UNIXLIB) 

moc_cpp:    $(MOC_CPP)

depend:
	@makedepend -o.$(OPT)  -fgnumakefile -I$(PIGALEPATH)/incl -I$(PIGALEPATH) -Y   $(FILES_WO_MOC)  2> /dev/null

nodepend:
	@makedepend -o.$(OPT)  -fgnumakefile -Y    2> /dev/null
.PHONY: md all
# DO NOT DELETE

CanvasGrid.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tbase.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tmessage.h
CanvasGrid.opt: ../../pigale/incl/TAXI/graphs.h
CanvasGrid.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tprop.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tsvector.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tdebug.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Errors.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tpropio.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tstring.h
CanvasGrid.opt: ../../pigale/incl/TAXI/propdef.h
CanvasGrid.opt: ../../pigale/incl/TAXI/Tpoint.h
CanvasGrid.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
CanvasGrid.opt: ../../pigale/incl/TAXI/random.h GraphWidget.h
CanvasGrid.opt: ../../pigale/incl/QT/pigaleQcolors.h
CanvasGrid.opt: ../../pigale/incl/QT/Misc.h
CanvasGrid.opt: ../../pigale/incl/QT/pigaleCanvas.h
CanvasGrid.opt: ../../pigale/incl/QT/grid.h
CanvasGrid.opt: ../../pigale/incl/QT/GraphWidgetPrivate.h mouse_actions.h
CanvasGrid.opt: gprop.h ../../pigale/incl/QT/Action_def.h
CanvasItem.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tbase.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tmessage.h
CanvasItem.opt: ../../pigale/incl/TAXI/graphs.h
CanvasItem.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tprop.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tsvector.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tdebug.h
CanvasItem.opt: ../../pigale/incl/TAXI/Errors.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tpropio.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tstring.h
CanvasItem.opt: ../../pigale/incl/TAXI/propdef.h
CanvasItem.opt: ../../pigale/incl/TAXI/Tpoint.h
CanvasItem.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
CanvasItem.opt: ../../pigale/incl/TAXI/random.h GraphWidget.h mouse_actions.h
CanvasItem.opt: ../../pigale/incl/QT/pigaleQcolors.h
CanvasItem.opt: ../../pigale/incl/QT/Misc.h
CanvasItem.opt: ../../pigale/incl/QT/pigaleCanvas.h
CanvasItem.opt: ../../pigale/incl/QT/grid.h
CanvasItem.opt: ../../pigale/incl/QT/GraphWidgetPrivate.h
CanvasSpring.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tbase.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tmessage.h
CanvasSpring.opt: ../../pigale/incl/TAXI/graphs.h
CanvasSpring.opt: ../../pigale/incl/TAXI/graph.h
CanvasSpring.opt: ../../pigale/incl/TAXI/elmt.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tprop.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tsvector.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tdebug.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Errors.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tpropio.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tstring.h
CanvasSpring.opt: ../../pigale/incl/TAXI/propdef.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tpoint.h
CanvasSpring.opt: ../../pigale/incl/TAXI/color.h
CanvasSpring.opt: ../../pigale/incl/TAXI/Tfile.h
CanvasSpring.opt: ../../pigale/incl/TAXI/random.h GraphWidget.h
CanvasSpring.opt: mouse_actions.h gprop.h ../../pigale/incl/QT/Action_def.h
CanvasSpring.opt: ../../pigale/incl/QT/pigaleQcolors.h
CanvasSpring.opt: ../../pigale/incl/QT/Misc.h
CanvasSpring.opt: ../../pigale/incl/QT/pigaleCanvas.h
CanvasSpring.opt: ../../pigale/incl/QT/grid.h
CanvasSpring.opt: ../../pigale/incl/QT/GraphWidgetPrivate.h
CanvasSpring.opt: ../../pigale/incl/QT/clientEvent.h
ClientSocket.opt: ClientSocket.h ../../pigale/incl/config.h
ClientSocket.opt: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tmessage.h
ClientSocket.opt: ../../pigale/incl/TAXI/graphs.h
ClientSocket.opt: ../../pigale/incl/TAXI/graph.h
ClientSocket.opt: ../../pigale/incl/TAXI/elmt.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tprop.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tsvector.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tdebug.h
ClientSocket.opt: ../../pigale/incl/TAXI/Errors.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tpropio.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tstring.h
ClientSocket.opt: ../../pigale/incl/TAXI/propdef.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tpoint.h
ClientSocket.opt: ../../pigale/incl/TAXI/color.h
ClientSocket.opt: ../../pigale/incl/TAXI/Tfile.h
ClientSocket.opt: ../../pigale/incl/TAXI/random.h pigaleWindow.h
ClientSocket.opt: ../../pigale/incl/QT/Misc.h
ClientSocket.opt: ../../pigale/incl/QT/Action_def.h
ClientSocket.opt: ../../pigale/incl/QT/clientEvent.h GraphWidget.h GraphGL.h
ClientSocket.opt: GraphSym.h mouse_actions.h gprop.h LineEditNum.h
ClientSocket.opt: ../../pigale/incl/QT/Handler.h
ClientSocket.opt: ../../pigale/incl/QT/pigalePaint.h
ClientSocket.opt: ../../pigale/incl/QT/pigaleCanvas.h
ClientSocket.opt: ../../pigale/incl/QT/grid.h
EmbedCurves.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tbase.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tmessage.h
EmbedCurves.opt: ../../pigale/incl/TAXI/graphs.h
EmbedCurves.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tprop.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tsvector.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tdebug.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Errors.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tpropio.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tstring.h
EmbedCurves.opt: ../../pigale/incl/TAXI/propdef.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tpoint.h
EmbedCurves.opt: ../../pigale/incl/TAXI/color.h
EmbedCurves.opt: ../../pigale/incl/TAXI/Tfile.h
EmbedCurves.opt: ../../pigale/incl/TAXI/random.h ../../pigale/incl/QT/Misc.h
EmbedCurves.opt: ../../pigale/incl/QT/Action_def.h GraphWidget.h
EmbedCurves.opt: ../../pigale/incl/QT/pigaleCanvas.h
EmbedCurves.opt: ../../pigale/incl/QT/grid.h
EmbedCurves.opt: ../../pigale/incl/QT/GraphWidgetPrivate.h
glcontrolwidget.opt: ../../pigale/incl/TAXI/Tbase.h glcontrolwidget.h
gprop.opt: gprop.h ../../pigale/incl/QT/Action_def.h
gprop.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tbase.h
gprop.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tdebug.h
gprop.opt: ../../pigale/incl/TAXI/Errors.h pigaleWindow.h
gprop.opt: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tmessage.h
gprop.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
gprop.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tpropio.h
gprop.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
gprop.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
gprop.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
gprop.opt: ../../pigale/incl/QT/Misc.h
GraphGL.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
GraphGL.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
GraphGL.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
GraphGL.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
GraphGL.opt: ../../pigale/incl/TAXI/Tsvector.h
GraphGL.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
GraphGL.opt: ../../pigale/incl/TAXI/Tpropio.h
GraphGL.opt: ../../pigale/incl/TAXI/Tstring.h
GraphGL.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
GraphGL.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
GraphGL.opt: ../../pigale/incl/TAXI/random.h GraphGL.h glcontrolwidget.h
GraphGL.opt: mouse_actions.h ../../pigale/incl/QT/GLWindow.h
GraphGL.opt: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/pigaleQcolors.h
GraphGL.opt: ../../pigale/incl/TAXI/netcut.h ../../pigale/incl/TAXI/embedrn.h
GraphGL.opt: ../../pigale/incl/config.h
graphml.opt: ../../pigale/incl/QT/graphml.h ../../pigale/incl/TAXI/graphs.h
graphml.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/graph.h
graphml.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
graphml.opt: ../../pigale/incl/TAXI/Tsvector.h
graphml.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
graphml.opt: ../../pigale/incl/TAXI/Tpropio.h
graphml.opt: ../../pigale/incl/TAXI/Tstring.h
graphml.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
graphml.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/config.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tpoint.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tbase.h
graphmlparser.opt: ../../pigale/incl/QT/graphml.h
graphmlparser.opt: ../../pigale/incl/TAXI/graphs.h
graphmlparser.opt: ../../pigale/incl/TAXI/graph.h
graphmlparser.opt: ../../pigale/incl/TAXI/elmt.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tprop.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tsvector.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tdebug.h
graphmlparser.opt: ../../pigale/incl/TAXI/Errors.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tpropio.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tstring.h
graphmlparser.opt: ../../pigale/incl/TAXI/propdef.h
graphmlparser.opt: ../../pigale/incl/TAXI/Tfile.h
GraphSym.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
GraphSym.opt: ../../pigale/incl/TAXI/Tbase.h
GraphSym.opt: ../../pigale/incl/TAXI/Tmessage.h
GraphSym.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
GraphSym.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
GraphSym.opt: ../../pigale/incl/TAXI/Tsvector.h
GraphSym.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
GraphSym.opt: ../../pigale/incl/TAXI/Tpropio.h
GraphSym.opt: ../../pigale/incl/TAXI/Tstring.h
GraphSym.opt: ../../pigale/incl/TAXI/propdef.h
GraphSym.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
GraphSym.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
GraphSym.opt: GraphSym.h ../../pigale/incl/QT/SymWindow.h
GraphSym.opt: ../../pigale/incl/QT/pigaleQcolors.h
GraphSym.opt: ../../pigale/incl/QT/Misc.h
Handler.opt: ../../pigale/incl/QT/Handler.h ../../pigale/incl/QT/Action_def.h
Handler.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
Handler.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
Handler.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Handler.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Handler.opt: ../../pigale/incl/TAXI/Tsvector.h
Handler.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Handler.opt: ../../pigale/incl/TAXI/Tpropio.h
Handler.opt: ../../pigale/incl/TAXI/Tstring.h
Handler.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
Handler.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
Handler.opt: ../../pigale/incl/TAXI/random.h ../../pigale/incl/QT/Misc.h
LineEditNum.opt: LineEditNum.h
Macro.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
Macro.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
Macro.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Macro.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Macro.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Macro.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Macro.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Macro.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
Macro.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
Macro.opt: GraphWidget.h mouse_actions.h LineEditNum.h
Macro.opt: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Action_def.h
Macro.opt: ../../pigale/incl/TAXI/Tgf.h
main.opt: ../../pigale/incl/config.h pigaleWindow.h
main.opt: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
main.opt: ../../pigale/incl/TAXI/Tmessage.h ../../pigale/incl/TAXI/graphs.h
main.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
main.opt: ../../pigale/incl/TAXI/Tprop.h ../../pigale/incl/TAXI/Tsvector.h
main.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
main.opt: ../../pigale/incl/TAXI/Tpropio.h ../../pigale/incl/TAXI/Tstring.h
main.opt: ../../pigale/incl/TAXI/propdef.h ../../pigale/incl/TAXI/Tpoint.h
main.opt: ../../pigale/incl/TAXI/color.h ../../pigale/incl/TAXI/Tfile.h
main.opt: ../../pigale/incl/TAXI/random.h ../../pigale/incl/QT/Misc.h
MiscQt.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
MiscQt.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
MiscQt.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
MiscQt.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
MiscQt.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
MiscQt.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
MiscQt.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
MiscQt.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
MiscQt.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
MiscQt.opt: GraphWidget.h
mouse_actions.opt: mouse_actions.h GraphWidget.h GraphGL.h
pigaleCanvas.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tbase.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tmessage.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/graphs.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/graph.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/elmt.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tprop.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tsvector.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tdebug.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Errors.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tpropio.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tstring.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/propdef.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tpoint.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/color.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/Tfile.h
pigaleCanvas.opt: ../../pigale/incl/TAXI/random.h GraphWidget.h
pigaleCanvas.opt: mouse_actions.h gprop.h ../../pigale/incl/QT/Action_def.h
pigaleCanvas.opt: ../../pigale/incl/QT/pigaleQcolors.h
pigaleCanvas.opt: ../../pigale/incl/QT/Misc.h
pigaleCanvas.opt: ../../pigale/incl/QT/pigaleCanvas.h
pigaleCanvas.opt: ../../pigale/incl/QT/grid.h
pigaleCanvas.opt: ../../pigale/incl/QT/GraphWidgetPrivate.h
pigalePaint.opt: pigaleWindow.h ../../pigale/incl/Pigale.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tbase.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tmessage.h
pigalePaint.opt: ../../pigale/incl/TAXI/graphs.h
pigalePaint.opt: ../../pigale/incl/TAXI/graph.h ../../pigale/incl/TAXI/elmt.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tprop.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tsvector.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tdebug.h
pigalePaint.opt: ../../pigale/incl/TAXI/Errors.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tpropio.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tstring.h
pigalePaint.opt: ../../pigale/incl/TAXI/propdef.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tpoint.h
pigalePaint.opt: ../../pigale/incl/TAXI/color.h
pigalePaint.opt: ../../pigale/incl/TAXI/Tfile.h
pigalePaint.opt: ../../pigale/incl/TAXI/random.h
pigalePaint.opt: ../../pigale/incl/QT/pigalePaint.h
pigalePaint.opt: ../../pigale/incl/QT/pigaleQcolors.h
pigalePaint.opt: ../../pigale/incl/QT/Misc.h
pigaleWindow.opt: ../../pigale/incl/config.h pigaleWindow.h
pigaleWindow.opt: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tmessage.h
pigaleWindow.opt: ../../pigale/incl/TAXI/graphs.h
pigaleWindow.opt: ../../pigale/incl/TAXI/graph.h
pigaleWindow.opt: ../../pigale/incl/TAXI/elmt.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tprop.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tsvector.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tdebug.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Errors.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tpropio.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tstring.h
pigaleWindow.opt: ../../pigale/incl/TAXI/propdef.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tpoint.h
pigaleWindow.opt: ../../pigale/incl/TAXI/color.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tfile.h
pigaleWindow.opt: ../../pigale/incl/TAXI/random.h
pigaleWindow.opt: ../../pigale/incl/TAXI/Tgf.h GraphWidget.h GraphGL.h
pigaleWindow.opt: GraphSym.h mouse_actions.h gprop.h
pigaleWindow.opt: ../../pigale/incl/QT/Action_def.h LineEditNum.h
pigaleWindow.opt: ../../pigale/incl/QT/pigaleWindow_doc.h
pigaleWindow.opt: ../../pigale/incl/QT/Misc.h ../../pigale/incl/QT/Handler.h
pigaleWindow.opt: ../../pigale/incl/QT/Action.h
pigaleWindow.opt: ../../pigale/incl/QT/pigalePaint.h
pigaleWindow.opt: ../../pigale/incl/QT/pigaleCanvas.h
pigaleWindow.opt: ../../pigale/incl/QT/grid.h
pigaleWindow.opt: ../../pigale/incl/QT/clientEvent.h icones/fileopen.xpm
pigaleWindow.opt: icones/filenew.xpm icones/fileprint.xpm icones/filesave.xpm
pigaleWindow.opt: icones/info.xpm icones/sleft.xpm icones/sright.xpm
pigaleWindow.opt: icones/sreload.xpm icones/help.xpm icones/xman.xpm
pigaleWindow.opt: icones/sleftarrow.xpm icones/srightarrow.xpm
pigaleWindow.opt: icones/sfilesave.xpm icones/macroplay.xpm icones/film.xpm
Settings.opt: ../../pigale/incl/config.h pigaleWindow.h
Settings.opt: ../../pigale/incl/Pigale.h ../../pigale/incl/TAXI/Tbase.h
Settings.opt: ../../pigale/incl/TAXI/Tmessage.h
Settings.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Settings.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Settings.opt: ../../pigale/incl/TAXI/Tsvector.h
Settings.opt: ../../pigale/incl/TAXI/Tdebug.h ../../pigale/incl/TAXI/Errors.h
Settings.opt: ../../pigale/incl/TAXI/Tpropio.h
Settings.opt: ../../pigale/incl/TAXI/Tstring.h
Settings.opt: ../../pigale/incl/TAXI/propdef.h
Settings.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
Settings.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
Settings.opt: mouse_actions.h LineEditNum.h gprop.h
Settings.opt: ../../pigale/incl/QT/Action_def.h ../../pigale/incl/QT/Misc.h
Settings.opt: ../../pigale/incl/QT/Handler.h
Test.opt: GraphWidget.h pigaleWindow.h ../../pigale/incl/Pigale.h
Test.opt: ../../pigale/incl/TAXI/Tbase.h ../../pigale/incl/TAXI/Tmessage.h
Test.opt: ../../pigale/incl/TAXI/graphs.h ../../pigale/incl/TAXI/graph.h
Test.opt: ../../pigale/incl/TAXI/elmt.h ../../pigale/incl/TAXI/Tprop.h
Test.opt: ../../pigale/incl/TAXI/Tsvector.h ../../pigale/incl/TAXI/Tdebug.h
Test.opt: ../../pigale/incl/TAXI/Errors.h ../../pigale/incl/TAXI/Tpropio.h
Test.opt: ../../pigale/incl/TAXI/Tstring.h ../../pigale/incl/TAXI/propdef.h
Test.opt: ../../pigale/incl/TAXI/Tpoint.h ../../pigale/incl/TAXI/color.h
Test.opt: ../../pigale/incl/TAXI/Tfile.h ../../pigale/incl/TAXI/random.h
Test.opt: ../../pigale/incl/QT/Action_def.h ../../pigale/incl/QT/Misc.h
Test.opt: ../../pigale/incl/QT/pigaleCanvas.h ../../pigale/incl/QT/grid.h
Test.opt: ../../pigale/incl/QT/GraphWidgetPrivate.h
